neotoolkit/dummy

internal/server/handler.go
test/case/get-example-pagination/openapi3.yml
test/case/get-example-pagination/users/GET/response.json

Add pagination

---

internal/server/handler.go

Add support create data in POST

---

internal/server/handler.go
test/case/set-status-code-500/header.txt
test/case/set-status-code-500/openapi3.yml
test/dummy_test.go

Add support 500

---

.github/workflows/ci.yml
internal/server/handler.go
internal/server/handler_test.go

feature: Add test and refactor GetLastPathSegment func

---

internal/server/handler.go
internal/server/handler_test.go

feature: Add remove trailing slash func

---

internal/openapi3/path.go
internal/server/handler.go
test/case/put-patch-example/openapi3.yml
test/case/put-patch-example/users/PATCH/response.json
test/case/put-patch-example/users/PUT/response.json

feature: Add support PUT and PATCH methods

---

README.md

feature: Add badges

---

.github/workflows/ci.yml

feature: Add coverage report to CI

---

internal/server/handler.go
internal/server/handler_test.go

feature: Add test

---

.github/workflows/ci.yml

feature: Add integration test step

---

internal/server/handler.go
internal/server/handler_test.go

feature: Add path by mask detect tests

---

.github/workflows/ci.yml

feature: Add race for unit tests

---

go.mod
go.sum
internal/server/handler.go
internal/server/handler_test.go

Add package `github.com/stretchr/testify` for easy testing

add function for clear url from reference in path #107

---

internal/logger/logger_test.go

Add logger test

---

internal/openapi3/components.go
internal/openapi3/openapi3.go
internal/openapi3/schema.go

Add components

---

internal/openapi3/parameter.go
internal/openapi3/schema.go
internal/server/handler.go

Add more OpenAPI fields and small refactoring

---

go.mod
test/dummy_test.go
test/testdata/patch-with-example/openapi3.yml
test/testdata/patch-with-example/pact.json
test/testdata/put-with-example/openapi3.yml
test/testdata/put-with-example/pact.json

feature: Add put and patch tests

---

internal/openapi3/example.go
internal/openapi3/example_test.go
internal/openapi3/mediatype.go
internal/server/handler.go

refactor: Move some helper to type method

---

internal/openapi3/example_test.go

refactor: Sort imports

---

internal/openapi3/mediatype.go
internal/openapi3/mediatype_test.go
internal/server/handler.go

refactor: Rename response methods

---

internal/openapi3/mediatype_test.go

test: Change test case

---

internal/server/handler.go
internal/server/handler_test.go
test/log/pact.log

changed function name from PathByMaskDetect to PathByParamDetect

---

internal/server/handler.go
test/testdata/put-without-example/openapi3.yml
test/testdata/put-without-example/pact.json

feature: Add support edit data in PUT and PATCH methods

---

internal/server/handler.go
internal/server/server.go
test/dummy_test.go

refactor: Add handler as other type

---

internal/server/handler.go

refactor: Small refactor

---

internal/server/handler.go
internal/server/handler_test.go

Signed-off-by: Login Victor <batazor111@evrone.com>

feature: add refSplit #132

---

internal/server/handler.go
internal/server/server.go
test/testdata/trailing-slash/openapi3.yml
test/testdata/trailing-slash/pact.json

feature: Add trailing slash case

---

internal/server/handler.go
internal/server/handler_test.go
internal/server/server.go
test/dummy_test.go
test/testdata/fragment/openapi3.yml
test/testdata/fragment/pact.json

feature: Move handlers methods from Server to Handlers type

---

internal/openapi3/mediatype_test.go

test: Add data test

---

README.md
examples/docker/Dockerfile
examples/docker/README.md
examples/docker/openapi3.yml

docs: Add usage example via docker

---

internal/server/handler.go
test/testdata/put-without-example2/openapi3.yml
test/testdata/put-without-example2/pact.json

feature: Move by id case from handlers to init handlers

---

internal/server/handler.go
test/testdata/get-examples2/openapi3.yml
test/testdata/get-examples2/pact.json

feature: Add test when try add data in POST method but GET in this path have X-Example header

---

internal/server/handler.go
internal/server/handler_test.go
internal/server/server.go

feature: Change header type in Handler type

---

test/testdata/crud-example/openapi3.yml
test/testdata/crud-example/pact.json

feature: Add CRUD test

---

go.mod
go.sum
internal/faker/faker.go
internal/faker/faker_test.go
internal/faker/uuid.go
internal/faker/uuid_test.go

feature: Add faker with UUID generator

---

go.mod
go.sum
internal/openapi3/schema.go

added Faker to schema

---

internal/openapi3/response.go

Тесты прошли - неудивительно, изменений минимум.
Не понял, надо ли дополнять тесты этим полем?

Added Description field into Response

---

internal/faker/boolean.go
internal/faker/boolean_test.go
internal/faker/faker.go

feature: Add random boolean for faker

---

internal/faker/boolean_test.go
internal/openapi3/example_test.go

fix: Fix tests

---

internal/faker/faker.go
internal/faker/person.go
internal/faker/person_test.go

feature: Add male and female names method and gender method

---

internal/faker/boolean_test.go
internal/faker/faker_test.go
internal/faker/uuid_test.go
internal/openapi3/example_test.go
internal/server/handler_test.go

Issue #121
Added the use of require.Equal (t, tt.want, got) where it was not. 
I also added the parallelism of running tests - it did not give a strong increase, but nothing seems to break.

Updated test

---

internal/command/server.go
internal/server/handler.go
internal/server/server.go

feature: Add NewHandlers func

---

internal/faker/person_test.go

feature: Add Parallel in tests

---

internal/faker/faker.go
internal/faker/internet.go
internal/faker/internet_test.go
internal/faker/person.go

feature: Add GTLC, domain, username and email generator

---

internal/command/executor.go
internal/config/config.go
internal/config/server.go
internal/faker/boolean.go
internal/faker/faker.go
internal/faker/internet.go
internal/faker/person.go
internal/faker/uuid.go
internal/logger/logger.go
internal/server/handler.go
internal/server/handler_test.go
internal/server/server.go

feature: Add basic description of functions

---

internal/faker/internet_test.go
internal/faker/person_test.go
internal/server/handler_test.go

refactor: Test refactor

---

internal/server/handler.go

refactor: Handler refactor

---

internal/server/handler.go
internal/server/handler_test.go

Issue #123
В общем-то, ты сам ее уже написал, я только тестов докинул

Added path param name removing parentheses function

---

internal/server/handler_test.go

refactor: Refactor test

---

internal/faker/faker.go
internal/faker/faker_test.go
internal/server/handler_test.go

feature: Add random data faker method

---

internal/faker/faker.go
internal/faker/faker_test.go

refactor: Refactor faker

---

internal/openapi3/info.go
internal/openapi3/openapi3.go
internal/openapi3/parse_test.go
internal/openapi3/testdata/openapi3.yml

See #175
Add Info struct to OpenAPI, cause Info Object is required.
Also test parsing function (only yaml file).

Parse Info Object

---

.golangci.yml
internal/openapi3/schema.go
internal/openapi3/schema_test.go

Add blackbox

---

internal/faker/faker.go
internal/faker/faker_test.go

Add faker alias

---

.github/workflows/ci.yml

Change path for testing

---

internal/openapi3/example_test.go

Fix GetKeys test

---

internal/apischema/apischema.go
internal/apischema/apischema_test.go
internal/apischema/find.go
internal/openapi3/parse.go
internal/openapi3/parse_test.go
internal/openapi3/schema_test.go
internal/server/handler.go
internal/server/server.go
test/dummy_test.go

See this components diagram https://lucid.app/lucidchart/2889e271-7a06-4425-a768-dd39dd21e9a0/edit?invitationId=inv_533f99fc-87b6-4c52-9ffc-71e0607e5d18
`apischema` is domain layer. All others depend on it.
Separate parsing OpenAPI v3 and mocking responses processes.
It's dirty enough implementation. But now we can design subsystems easier.

Refactor architecture

---

internal/openapi3/parse.go
internal/server/server.go
test/testdata/set-status-code/openapi3.yml
test/testdata/set-status-code/pact.json

refactor(server): Add set status code function

---

internal/apischema/apischema_test.go
internal/apischema/find_test.go
internal/faker/boolean_test.go
internal/faker/faker_test.go
internal/faker/person_test.go
internal/faker/uuid_test.go
internal/openapi3/example_test.go
internal/openapi3/parse_test.go
internal/openapi3/schema_test.go

refactor(all): Remove parallel

---

README.md

docs: Change title in README

---

internal/command/server.go
internal/server/server.go

internal: Add logs

---

internal/command/server.go
internal/config/config.go
internal/config/logger.go

feature(config): Add logger

---

internal/command/server.go
internal/logger/logger.go
test/dummy_test.go

feature(logger): Add logger level

---

.github/workflows/ci.yml
.github/workflows/lint.yml

feature(ci): Add lint

---

.github/workflows/lint.yml

feature(ci): Add check mod

---

.github/workflows/test.yml

feature(ci): Add test

---

internal/server/handler.go
test/dummy_test.go

refactor(server): Remove unused

---

cmd/dummy/main.go
examples/docker/Dockerfile
examples/docker/openapi3.yml

feature(examples): Add new runner

---

internal/apischema/find_test.go

refactor(apischema): Refactor fuzz test

---

internal/middleware/logging.go
internal/server/server.go

feature(middleware): Add logging middleware

---

go.mod
go.sum
internal/openapi3/example.go
internal/openapi3/mediatype_test.go
internal/openapi3/parse.go

feature(all): update yaml lib

---

internal/apischema/apischema.go
internal/openapi3/openapi3.go
internal/openapi3/parse.go
internal/server/server.go

refactor(all): nil check

---

internal/openapi3/example.go
internal/openapi3/parse.go

refactor(all): remove shadowing

---

internal/middleware/logging.go

feature(middleware): add response for logging

---

internal/openapi3/parse.go

fix(openapi3): fix empty items case

---

.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/test.yml

feature(ci): Add path-ignore

---

.github/workflows/ci.yml

ci(.github/workflows): Add check dependencies step

---

internal/api/apischema.go
internal/api/apischema_test.go
internal/api/find.go
internal/api/find_test.go
internal/openapi3/parse.go
internal/openapi3/parse_test.go
internal/server/handler.go

refactor: rename package

---

internal/openapi3/build.go
internal/openapi3/parse_test.go

perf(openapi3): add map prealloc

---

test/testdata/get-example/openapi3.yml
test/testdata/get-example2/openapi3.yml
test/testdata/get-examples/openapi3.yml
test/testdata/get-properties-examples/openapi3.yml
test/testdata/get-with-path-param-example/openapi3.yml

style(test): format yml

---

.github/workflows/ci.yml

ci(.github/workflows): remove race and change path

---

internal/logger/logger_test.go

test(logger): add logger tests

---

internal/exitcode/exitcode.go
internal/middleware/logging.go
internal/openapi3/build.go
internal/openapi3/components.go
internal/openapi3/content.go
internal/openapi3/example.go
internal/openapi3/mediatype.go
internal/openapi3/openapi3.go
internal/openapi3/operation.go
internal/openapi3/parameter.go
internal/openapi3/parse.go
internal/openapi3/path.go
internal/openapi3/requestbody.go
internal/openapi3/response.go
internal/openapi3/schema.go
internal/read/read.go

docs(all): add empty description

---

internal/config/config_test.go

test(config): add config test

---

examples/docker/Dockerfile

docs(examples/docker): change dockerfile

---

.github/workflows/ci.yml

ci(.github/workflows): remove ruby and pact, add race for test

---

internal/read/read_test.go
internal/read/testdata/openapi3.yml

test(read): add read test

---

.github/workflows/ci.yml

ci(.github/workflows): remove verbose and fix covermode

---

.github/workflows/ci.yml
.github/workflows/coverage.yml

ci(.github/workflows): add coverage job

---

internal/api/find.go
internal/api/find_test.go

test(api): add test for PathByParamDetect and FindResponseError

---

internal/api/apischema.go
internal/api/find.go
internal/openapi3/openapi3.go
internal/openapi3/parse.go

docs(internal): add empty description

---

internal/openapi3/parse.go
internal/openapi3/parse_test.go

test(openapi3): add ObjectExampleError test

---

internal/openapi3/openapi3.go
internal/openapi3/openapi3_test.go

test(openapi3): add SchemaError test

---

.github/workflows/coverage.yml

ci(.github/workflows): change job

---

internal/openapi3/openapi3.go
internal/openapi3/openapi3_test.go

test(openapi3): add LookupByReference test

---

internal/config/config_test.go
internal/logger/logger_test.go
internal/openapi3/openapi3_test.go
internal/read/read_test.go

style(all): format all

---

internal/openapi3/build.go
internal/openapi3/parse.go
internal/openapi3/parse_test.go

test(internal/openapi3): add tests

---

internal/faker/faker_test.go
internal/logger/logger_test.go
internal/openapi3/parse_test.go
internal/read/read_test.go

test(all): add RemoveTrailingSlash test and test format

---

cmd/dummy/main.go
go.mod
go.sum

feat(cmd): add acmd

---

README.md
cmd/dummy/main.go

docs(all): change version

---

internal/api/find_test.go
internal/parse/parse.go

feat(parse): add spec type detector

---

internal/openapi3/openapi3.go
internal/parse/parse.go
internal/parse/parse_test.go
internal/parse/testdata/openapi3

feat(all): add openapi3 detect

---

go.mod
go.sum
internal/api/build.go
internal/api/build_test.go
internal/parse/parse.go

feat(openapi): use openapi parse as dependency

---

internal/parse/parse.go
internal/parse/parse_test.go

refactor(parse): rename OpenAPI const

---

internal/read/read.go
internal/read/read_test.go

test(read): add more tests

---

internal/parse/parse.go
internal/parse/parse_test.go

feat(parse): add check graphql schema file format

---

internal/parse/parse.go
internal/parse/parse_test.go
internal/parse/testdata/openapi.yml

feat(parse): add openapi parse case

---

internal/api/find_test.go

test(api): change PathByParamDetect test case

---

internal/api/find_test.go

test(api): add PathByParamDetect test case

---

internal/api/api_test.go

test(api): add more ExampleValue tests

---

internal/api/build.go
internal/api/build_test.go

test(api): Add ParseArrayExample, ParseObjectExample, Builder_Build tests

---

internal/api/build_test.go

test(api): Add Builder_Build error cases

---

go.mod
go.sum

chore(deps): update acmd

---

Makefile
README.md

feat(makefile): Add local run

---

cmd/dummy/main.go

fix: add flag parse

---

internal/api/build.go
internal/api/build_test.go

test(api): add builder add and set methods tests

---

README.md
examples/docker/Dockerfile
internal/parse/parse.go

docs: change example

---

.golangci.yml

chore(linter): add testpackage lint

---

README.md

docs(README): change description format

---

README.md

docs(README): change evrone logo link

---

.github/dependabot.yml
.github/workflows/build.yml

ci: add lint and update dependabot

---

internal/api/build_test.go

test(api): add more set method tests

---

internal/api/build.go
test/testdata/openapi.yml

fix(api): skip status less 200 or greatest or equal 300

---

go.mod
go.sum
internal/api/build.go

chore(openapi): update openapi lib

---

internal/middleware/logging_test.go

test(middleware): add logging test

---

internal/api/build.go
internal/api/build_test.go
internal/pkg/pathfmt/pathfmt.go
internal/pkg/pathfmt/pathfmt_test.go
internal/server/handler.go

feat(pkg/pathfmt): helper for format path add as package

---

internal/logger/logger.go
internal/parse/parse.go

refactor: refactor

---

internal/server/handler_test.go
internal/server/server_test.go

test(server): add server test

---

test/testdata/cases.yml

test: add test for set status code via header

---

internal/parse/parse.go
internal/parse/parse_test.go

feat: use ext for format check
